"""Added due amount and due date to CreditCard model

Revision ID: 17b9e1f6d71f
Revises: efa13b8d1744
Create Date: 2024-08-10 15:40:06.737684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b9e1f6d71f'
down_revision = 'efa13b8d1744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.drop_column('due_date')
        batch_op.drop_column('due_amount')

    # ### end Alembic commands ###
