"""Change credit_card_name to integer in Expense

Revision ID: bd00fcc25131
Revises: 9472aa966503
Create Date: 2024-07-26 22:30:07.009605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd00fcc25131'
down_revision = '9472aa966503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('credit_card_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'credit_card', ['credit_card_name'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('credit_card_name',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###
